# Generated by Django 4.0.2 on 2022-03-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_pessoa_email_pessoa_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='strin',
            field=models.BooleanField(default=False),
        ),
    ]
