# Generated by Django 4.0.2 on 2022-03-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_pessoa_strin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='strin',
        ),
    ]
