# Generated by Django 4.0.2 on 2022-03-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto_publicada',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
