# Generated by Django 4.0.2 on 2022-03-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_alter_receita_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='date',
            field=models.DateField(),
        ),
    ]
